---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: mongodb-storage
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-pv
spec:
  capacity:
    storage: 3Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: mongodb-storage
  local:
    path: /mnt
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - pixiu01 # 这里根据官网例子，要设置亲和性，改成节点名
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: mongodb-secret
data:
  username: YWRtaW4=
  password: MTIzNDU2
---
apiVersion: opstreelabs.in/v1alpha1
kind: MongoDB
metadata:
  name: mongodb
spec:
  kubernetesConfig:
    image: 'quay.io/opstree/mongo:v5.0.6'
    imagePullPolicy: IfNotPresent
    securityContext:
      fsGroup: 1001
  storage:
    accessModes:
      - ReadWriteOnce
    storageSize: 1Gi
    storageClass: gp2
  mongoDBSecurity:
    mongoDBAdminUser: admin
    secretRef:
      name: mongodb-secret
      key: password

