apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: rabbitmqcluster
spec:
  persistence:
    # storageClassName 自动创建 pv
    storageClassName: managed-nfs-storage
    storage: 1Gi
