apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: my-rabbitmq-cluster-operator
  namespace: operators
spec:
  channel: stable
  name: rabbitmq-cluster-operator
  source: operatorhubio-catalog
  sourceNamespace: olm